{% set version = "3.8.2" %}

package:
  name: pyside2ads
  version: {{ version }}

source:
  path: ../
  
build:
  number: 1
  script: python -m pip install . -vvv

requirements:
  build:
    - cmake>=3.13
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - clangdev

  host:
    - python {{ python }}
    - qt
    - qtadvanceddocking
    - pyside2
    - mesalib  # [unix]
    
  run:
    - {{ pin_compatible('python') }}
    - qtadvanceddocking
    - pyside2
    
test:
  imports:
    - PySide2Ads
    - PySide2Ads.QtAds

about:
  home: https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System
  license:  LGPL-2.1-only
  license_file: LICENSE
  summary: PySide2 binding for Qt-Advanced-Docking-System

extra:
  recipe-maintainers:
    - n-elie
